image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

onPullRequest:
  stage: test
  only:
  - merge_requests
  script:
  - apk add --no-cache bash
  - allowDockerBuildForUncommittedChanges=true ./hp onPullRequest

buildCicdDockerImage:
  stage: build
  image: docker:stable
  only:
  - gitlab
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker pull registry.gitlab.com/bob-bins/heartpoints.org/cicd:1.0.0 || docker build -t registry.gitlab.com/bob-bins/heartpoints.org/cicd:1.0.0 -f cicd.Dockerfile .
  - docker push registry.gitlab.com/bob-bins/heartpoints.org/cicd:1.0.0

deploy:
  stage: deploy
  only:
  - gitlab
  image: registry.gitlab.com/bob-bins/heartpoints.org/cicd:1.0.0
  script:
  - export gcpCicdServiceAccountCredentialsJson="$gcpCicdServiceAccountCredentialsJson"
  - ./hp onMasterMerge
