apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: heartpoints-org
  name: heartpoints-org
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heartpoints-org
      name: heartpoints-org
    spec:
      containers:
      - name: heartpoints-org
        image: {{image}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 25m
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - curl
            - http://localhost:5001
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heartpoints-ingress
spec:
  backend:
    serviceName: heartpoints-org
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: heartpoints-org
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: heartpoints-org
