version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  onPullRequest:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./heartpoints.sh onPullRequest
      - run: pwd && ls -al
      - codecov/upload:
          file: coverage/coverage-final.json
  onMasterMerge:
    docker:
      - image: gcr.io/heartpoints-org/cicd:1.0.1
        auth:
          username: _json_key
          password: $gcpCicdServiceAccountCredentialsJson
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./heartpoints.sh onMasterMerge
workflows:
  version: 2
  pipeline:
    jobs:
      - onPullRequest:
          filters:
            branches:
              ignore: master
      - onMasterMerge:
          filters:
            branches:
              only: master