version: 2
jobs:
  onPullRequest:
    docker:
      - image: gcr.io/heartpoints-org/cicd:1.0.0 # todo: document how this image got there
        auth:
          username: _json_key
          password: $gcpCicdServiceAccountCredentialsJson
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./heartpoints.sh onMasterMerge
  onMasterMerge:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            # echo 'export $gcpCicdServiceAccountCredentialsJson' >> $gcpCicdServiceAccountCredentialsJson
            ./heartpoints.sh onMasterMerge
      
workflows:
  version: 2
  pipeline:
    jobs:
      - onPullRequest:
          filters:
            branches:
              ignore: master
      - onMasterMerge:
          filters:
            branches:
              only: master