apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heartpoints-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: heartpoints-org
spec:
  backend:
    serviceName: heartpoints-org
    servicePort: 80